FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Heh heh heh...\p"
    .string "You found your way through my\n"
    .string "maze of illusions.\p"
    .string "Not many children make it this\n"
    .string "far without losing their nerve.\p"
    .string "Very well. Let me show you the\n"
    .string "true face of a ninja master.\p"
    .string "Poison creeps. Sleep steals away\n"
    .string "your senses.\p"
    .string "Come and taste the quiet dread of\n"
    .string "POISON-type POKéMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Hmph...\n"
    .string "Not even my tricks could fool you.\p"
    .string "Here.\n"
    .string "Take the SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "TOXIC is no ordinary poison.\n"
    .string "It sinks in deeper by the moment.\p"
    .string "The longer the battle drags on,\n"
    .string "the more it eats away at a foe.\p"
    .string "There is no escaping it once it\n"
    .string "takes hold.$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "The SOULBADGE you now hold will\n"
    .string "toughen your POKéMON's DEFENSE.\p"
    .string "It also grants you passage to\n"
    .string "SURF beyond these walls.\p"
    .string "One more thing, before you go...$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} received TM06\n"
    .string "from KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "Within that TM06 sleeps TOXIC,\n"
    .string "a secret art of my clan.\p"
    .string "Four hundred years old, and still\n"
    .string "no foe has found a cure for it.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Come now, make room for this.$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "Strength isn't the key for POKéMON.\n"
    .string "Do you understand this?\p"
    .string "POKéMON is about strategy!\p"
    .string "I'll show you how strategy can\n"
    .string "beat brute strength.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "What?\n"
    .string "Extraordinary!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "So, you mix brawn with brains?\n"
    .string "Good strategy!\p"
    .string "That's remarkable for a child\n"
    .string "TRAINER.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "I was a magician once upon a time.\p"
    .string "But I dreamt of becoming a ninja,\n"
    .string "so I joined this GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "I'm done for!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Even though I've lost, I will keep\n"
    .string "training according to the teachings\l"
    .string "of KOGA, my ninja master.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Let's see you beat my special\n"
    .string "techniques!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "You had me fooled!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "I like poison and sleep techniques,\n"
    .string "as they linger after battle!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Stop right there!\p"
    .string "The famed invisible walls of\n"
    .string "FUCHSIA GYM have you frustrated?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Whoa!\n"
    .string "You've got it!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "You impressed me!\n"
    .string "Here's a hint!\p"
    .string "Look very closely for gaps in the\n"
    .string "invisible walls!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "I also study the way of the ninja\n"
    .string "with Master KOGA!\p"
    .string "Ninja have a long history of using\n"
    .string "animals!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "I still have much to learn.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Master KOGA comes from a long line\n"
    .string "of ninjas.\p"
    .string "What did you descend from?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "You're more skilled than I'd\n"
    .string "thought!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Where there is light, there is\n"
    .string "shadow!\p"
    .string "Light and shadow!\n"
    .string "Which do you choose?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "FUCHSIA GYM is a tricked-up place.\n"
    .string "It's riddled with invisible walls!\p"
    .string "KOGA might appear close, but he's\n"
    .string "blocked off.\p"
    .string "You have to find gaps in the walls\n"
    .string "to reach him.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "It's amazing how ninja can terrify,\n"
    .string "even now!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

