SaffronCity_Gym_Text_SabrinaIntro::
    .string "I foresaw your arrival…\n"
    .string "down to this very moment.\p"
    .string "Psychic power has followed me\n"
    .string "since I was a small child.\p"
    .string "It started with a spoon,\n"
    .string "carelessly tossed. It bent for me.\p"
    .string "Battling bores me, if I'm honest.\n"
    .string "But you're here, so entertain me.{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "…I did not foresee this.\n"
    .string "How curious.\p"
    .string "I suppose I didn't try quite\n"
    .string "hard enough to win.\p"
    .string "Your victory has earned you the\n"
    .string "MARSHBADGE.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Psychic power was never rare.\n"
    .string "I simply learned to listen for it.\p"
    .string "You have it too, {PLAYER}.\n"
    .string "You just haven't learned to listen.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "The MARSHBADGE lets POKéMON up\n"
    .string "to Lv. 70 obey you.\p"
    .string "Anything stronger grows wild and\n"
    .string "stops listening to your orders.\p"
    .string "Best not to overlevel them,\n"
    .string "unless you like being ignored.\p"
    .string "Here. Take this TM as well.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} received TM04 from\n"
    .string "SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04 is CALM MIND.\p"
    .string "It makes the POKéMON concentrate\n"
    .string "to raise both SP. ATK and SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Your BAG is full of other items.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA is far younger than I,\n"
    .string "but she has earned my respect.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Not good enough!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "In a battle of equals, the one\n"
    .string "with the stronger will wins.\p"
    .string "If you wish to beat SABRINA, focus\n"
    .string "and will yourself to victory.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Does our unseen power scare you?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "I never foresaw this!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC POKéMON fear only ghosts\n"
    .string "and bugs!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKéMON take on the appearance of\n"
    .string "their TRAINERS.\p"
    .string "Your POKéMON must be tough, then!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "I knew it!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "I have much to learn still…\p"
    .string "I must master PSYCHIC and teach it\n"
    .string "to my POKéMON…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "You understand, don't you?\p"
    .string "That power alone isn't enough to\n"
    .string "win in the world of POKéMON?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "I don't believe this!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA just wiped out the KARATE\n"
    .string "MASTER next door.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "You and I, our POKéMON shall\n"
    .string "battle!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "I lost after all!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "I knew that this was going to take\n"
    .string "place.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA is young, but she's also\n"
    .string "our highly skilled LEADER.\p"
    .string "You won't reach her easily!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Ow!\n"
    .string "Down and out!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "There used to be two POKéMON GYMS\n"
    .string "in SAFFRON.\p"
    .string "The FIGHTING DOJO next door lost\n"
    .string "its GYM status, though.\p"
    .string "We simply creamed them when we\n"
    .string "decided to have just one GYM.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON POKéMON GYM is famous for\n"
    .string "training psychics.\p"
    .string "You want to see SABRINA, don't\n"
    .string "you? I can tell!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "That's right! I used telepathy to\n"
    .string "read your mind!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "SABRINA's POKéMON use psychic\n"
    .string "power instead of force.\p"
    .string "FIGHTING POKéMON are especially\n"
    .string "weak against PSYCHIC POKéMON.\p"
    .string "They'll get destroyed before they\n"
    .string "can even aim a punch!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psychic power, huh?\p"
    .string "If I had that, I'd make a bundle\n"
    .string "at the slots!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

