Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Oh, hey! {PLAYER}!\p"
	.string "Heading for the POKéMON LEAGUE\n"
	.string "already? Ha, good one.\p"
	.string "You don't have a single BADGE\n"
	.string "yet, do you?\p"
	.string "The guard's not letting you\n"
	.string "through those gates without one.\p"
	.string "Anyway, enough about that. Has\n"
	.string "your POKéMON gotten any\l"
	.string "stronger since I last saw it?$"

Route22_Text_EarlyRivalDefeat::
	.string "Aw, come on!\n"
	.string "That was just luck!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Word is the POKéMON LEAGUE is\n"
	.string "packed with seriously tough\l"
	.string "TRAINERS.\p"
	.string "I've got some figuring out to do\n"
	.string "before I'm ready for that.\p"
	.string "Anyway, quit standing around and\n"
	.string "get moving already!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: Huh? {PLAYER}!\n"
	.string "Didn't expect to run into you\l"
	.string "out here!\p"
	.string "So, what, you're headed for the\n"
	.string "POKéMON LEAGUE too?\p"
	.string "All eight BADGES and everything?\n"
	.string "Not bad, not bad at all.\p"
	.string "Tell you what, humor me. Let's\n"
	.string "call this my warm-up before the\l"
	.string "big leagues.\p"
	.string "Come on, {PLAYER}!$"

Route22_Text_LateRivalDefeat::
	.string "What!? No way!\p"
	.string "I wasn't even trying, you know!$"

Route22_Text_LateRivalPostBattle::
	.string "Ha, good, that got the rust off.\n"
	.string "I'm plenty ready for the LEAGUE\l"
	.string "now.\p"
	.string "{PLAYER}, you could still use the\n"
	.string "practice, though.\p"
	.string "Not that you don't already know\n"
	.string "that. I'm outta here. Smell ya!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"

