CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hah-hah-hah!\p"
    .string "The name's BLAINE, red-hot LEADER\n"
    .string "of CINNABAR GYM!\p"
    .string "My POKéMON and I turn up the\n"
    .string "heat on every challenger!\p"
    .string "That's not just hot air, that's\n"
    .string "a promise!\p"
    .string "Hah! Better bring a BURN HEAL,\n"
    .string "or two, or ten!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "Gwahaha! Snuffed out cold!\n"
    .string "Not even embers left of me!\p"
    .string "You have earned the VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "FIRE BLAST is my magnum opus,\n"
    .string "the ultimate fire technique!\p"
    .string "Hah! Don't waste it on some\n"
    .string "soggy WATER POKéMON, now!$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "Hah! Here, catch, fresh off\n"
    .string "the volcano, the VOLCANOBADGE!\p"
    .string "It heightens the SPECIAL stats\n"
    .string "of your POKéMON.\p"
    .string "And I've got one more thing for\n"
    .string "you, so don't run off yet!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} received TM38\n"
    .string "from BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "TM38 contains FIRE BLAST, my\n"
    .string "pride and joy of a move!\p"
    .string "Teach it to a FIRE-type and\n"
    .string "watch the fireworks!\p"
    .string "VULPIX or CHARMELEON would be\n"
    .string "ideal candidates, hah!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Hah! Make some room, would you?\n"
    .string "This won't fit in a stuffed bag!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Do you know how hot POKéMON fire\n"
    .string "breath can get?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Yow!\n"
    .string "Hot, hot, hot!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Fire, or to be more precise,\n"
    .string "combustion…\p"
    .string "…Oxygen in the air…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "I was a thief, but I went straight\n"
    .string "as a TRAINER.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "I surrender!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "I get this uncontrollable urge to\n"
    .string "steal other people's POKéMON.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "I've studied POKéMON thoroughly.\n"
    .string "You can't win!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Waah!\n"
    .string "My studies were insufficient!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "My theories are too complicated\n"
    .string "for you to understand.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "I like using FIRE-type POKéMON.\n"
    .string "I just do.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "Too hot to handle!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "I wish there were a thief POKéMON.\n"
    .string "I'd use that!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "I know why BLAINE became a\n"
    .string "TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Our LEADER, BLAINE, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a fiery bird\n"
    .string "POKéMON appeared.\p"
    .string "Its light allowed BLAINE to find\n"
    .string "his way down safely.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "I've been to many GYMS, but this\n"
    .string "one best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Yowza!\n"
    .string "Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, NINETALES…\n"
    .string "Those are popular FIRE POKéMON.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Fire is weak against H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Oh!\n"
    .string "Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Water beats fire, of course.\p"
    .string "But fire melts ice, so the FIRE\n"
    .string "type beats ICE-type POKéMON.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "The hotheaded BLAINE is a FIRE\n"
    .string "POKéMON pro.\p"
    .string "Douse his spirits with water!\p"
    .string "You'd better take some\n"
    .string "BURN HEALS, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "You beat that firebrand!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "It's POKéMON Quiz time! Hah!\p"
    .string "Answer right, and the door swings\n"
    .string "wide open!\p"
    .string "Answer wrong, and a TRAINER's\n"
    .string "itching for a battle!\p"
    .string "Want to save your POKéMON for\n"
    .string "yours truly, the LEADER?\p"
    .string "Then think fast and answer\n"
    .string "right! Here we go!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "CATERPIE evolves into METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "There are nine certified POKéMON\n"
    .string "LEAGUE BADGES?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "POLIWAG evolves three times?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Are electric moves effective\n"
    .string "against GROUND-type POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "POKéMON of the same kind and level\n"
    .string "are not identical?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "TM28 contains TOMBSTONY?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "Correct! Hah, I knew you had\n"
    .string "the brains to match the heat!\p"
    .string "Go on through!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Ooh, sorry!\n"
    .string "That one's gonna burn!$"

