PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "What are you doing in a place\l"
    .string "like this? Your POKéMON keel\l"
    .string "over already?\p"
    .string "Ha, kidding, it's fine.\p"
    .string "Well, I can't do much for dead\n"
    .string "POKéMON, but I can make yours\l"
    .string "faint! Let's go!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "What?\n"
    .string "Oh, you sneak!\p"
    .string "And here I was going easy on\n"
    .string "you, too!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "So, how's your POKéDEX coming?\n"
    .string "I just caught a CUBONE, myself.\p"
    .string "Can't find a MAROWAK to save my\n"
    .string "life, though. Where are they\l"
    .string "hiding?\p"
    .string "Knowing my luck, there probably\n"
    .string "aren't any left around here.\p"
    .string "Anyway, I've got places to be,\n"
    .string "unlike some people.\p"
    .string "Smell ya later!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Even we could not identify the\n"
    .string "wayward ghosts.\p"
    .string "A SILPH SCOPE might be able to\n"
    .string "unmask them.$"

