FourIsland_Text_IslandSign::
    .string "FOUR ISLAND\n"
    .string "The Warm, Blue, Floe Island$"

FourIsland_Text_LoreleiHasReturned::
    .string "LORELEI has returned.\p"
    .string "Did she find the city life too\n"
    .string "stressful, I wonder?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "LORELEI has gone back.\p"
    .string "The LAPRAS she has, I imagine it\n"
    .string "to be the one she met as a child.\p"
    .string "I believe it was in ICEFALL CAVE\n"
    .string "that she caught it.\p"
    .string "Perhaps that POKéMON has been with\n"
    .string "her ever since.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hey!\n"
    .string "{PLAYER}!\p"
    .string "What are you even doing out here\n"
    .string "in the SEVII ISLANDS?\p"
    .string "Seriously, quit copying me. It's\n"
    .string "getting a little embarrassing.\p"
    .string "Anyway, I already got my POKéMON\n"
    .string "EGG, so this island's old news to\l"
    .string "me now.\p"
    .string "Heh, I bet you don't even know\n"
    .string "what a POKéMON EGG is.\p"
    .string "Good luck filling out that\n"
    .string "NATIONAL POKéDEX at this rate.\p"
    .string "Oh, hey, by the way, I ran into\n"
    .string "someone we both know around\l"
    .string "here.\p"
    .string "Go look around if you're curious.\n"
    .string "I would, but I've got better\l"
    .string "things to do.\p"
    .string "Be smelling ya!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Oh, you found me!\n"
    .string "Please don't tell LORELEI.\p"
    .string "Did you know that LORELEI has lots\n"
    .string "and lots of stuffed dolls?\p"
    .string "Every time she comes back to\n"
    .string "FOUR ISLAND, her collection grows!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Ooh, chilly!\p"
    .string "I made a slushie using ice I\n"
    .string "shaved inside ICEFALL CAVE.\p"
    .string "It's chilly and tasty!$"

FourIsland_Text_LoreleisHouse::
    .string "LORELEI'S HOUSE$"

